language: java

sudo: false # faster builds

os:
  - linux
  - osx

jdk:
  - oraclejdk8
  
script: 

  - mvn clean install
  
  - mvn cobertura:cobertura

after_success:
- bash <(curl -s https://codecov.io/bash)